name: Setup Node.js with pnpm
description: Composite action to setup Node.js, pnpm, and install dependencies with caching.

inputs:
  node-version:
    description: Node.js version to use
    required: false
    default: "22"
  install-command:
    description: Command to install dependencies
    required: false
    default: "pnpm install --frozen-lockfile"
  github-packages-token:
    description: Token for GitHub Packages npm registry auth (optional)
    required: false
    default: ""
  working-directory:
    description: Working directory for install command
    required: false
    default: "."

runs:
  using: composite
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v4

    - name: Setup Node.js ${{ inputs.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: pnpm

    - name: Configure GitHub Packages auth
      if: inputs.github-packages-token != ''
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: echo "//npm.pkg.github.com/:_authToken=${{ inputs.github-packages-token }}" >> .npmrc

    - name: Install dependencies
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: ${{ inputs.install-command }}
